[package]
name = "proxy-telegram-bot"
version = "0.0.1"
authors = ["Tikitko <bns.6587@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.10"

teloxide = "0.3.1"
teloxide-macros = "0.3.2"

tokio = { version =  "0.2.11", features = ["rt-threaded", "macros"] }
